api:
  base_url: "your_base_url"
  api_key: "your_api_key"

paths:
  data_dir: "./data"
  database_dir: "./data/merged_databases"
  gold_schema_linking_dir: "./data/gold_schema_linking"
  results_dir: "./results"
  logs_dir: "./logs"
  model_dir: "/data/xxx/models/Qwen2.5-0.5B"
  sft_data_dir: "./data/sft"
  sft_save_dir: "/data/xxx/saves/Qwen2.5-0.5B-router/sft"