train_file: "data/dpo/bird_train_dataset/classifier_train.json"
valid_file: "data/dpo/bird_train_dataset/classifier_valid.json"

# Training hyperparameters
output_dir: "/path/to/saves/Qwen2.5-0.5B-router/dpo/"
per_device_train_batch_size: 8
num_train_epochs: 12
fp16: True
learning_rate: 0.000001
loss_type: "sigmoid"
beta: 0.1
max_prompt_length: 512
max_completion_length: 128
max_length: 640
generate_during_eval: False
dataset_num_proc: None
remove_unused_columns: False
logging_steps: 100
save_steps: 100
eval_strategy: "steps"
eval_steps: 100
logging_dir: "/path/to/logs"


